# Project: Project1
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = tel_prog.o dosyaislemleri.o $(RES)
LINKOBJ  = tel_prog.o dosyaislemleri.o $(RES)
LIBS =  -L"D:/kurulumlar/Dev-Cpp/lib"  
INCS =  -I"D:/kurulumlar/Dev-Cpp/include" 
CXXINCS =  -I"D:/kurulumlar/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"D:/kurulumlar/Dev-Cpp/include/c++/3.4.2/backward"  -I"D:/kurulumlar/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"D:/kurulumlar/Dev-Cpp/include/c++/3.4.2"  -I"D:/kurulumlar/Dev-Cpp/include" 
BIN  = Project1.exe
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS)  
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before Project1.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "Project1.exe" $(LIBS)

tel_prog.o: tel_prog.cpp
	$(CPP) -c tel_prog.cpp -o tel_prog.o $(CXXFLAGS)

dosyaislemleri.o: dosyaislemleri.cpp
	$(CPP) -c dosyaislemleri.cpp -o dosyaislemleri.o $(CXXFLAGS)
